# Generated by Django 4.1.1 on 2022-09-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_product_watchlist_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_of_bids',
        ),
    ]
