# Generated by Django 4.1.1 on 2022-09-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_product_number_of_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
