# Generated by Django 4.1.1 on 2022-10-05 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_watchlist_product_watchlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=158)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+1 9999999999". Up to 15 digits is allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contactus',
            },
        ),
    ]
