# Generated by Django 4.1.1 on 2022-10-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_contactus_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='winner',
        ),
    ]
